export const STR = {
  title: "Tafelrunde",
  waitingHeadline: "Warte auf Mitspieler…",
  waitingHint: "Teile den Einladungslink unten. Sobald ihr bereit seid, tippt der erste Spieler auf „Los geht's“ – ihr könnt auch allein starten.",
  startBtn: "Los geht's",
  inviteLabel: "Einladungslink:",
  spectating: "Du schaust zu",
  yourTurn: "Du bist dran",
  waitingForTurn: (name) => `${name} ist am Zug`,
  enemyPhase: "Die Gegner sind am Zug…",
  roundLabel: (n) => `Runde ${n}`,
  heroNames: { waechter: "Wächter", wildhueter: "Wildhüter" },
  enemyNames: { raider: "Plünderer", archer: "Bogenschütze", captain: "Hauptmann" },
  cardMove: "Vorstoß",
  cardMoveHint: "Zieh bis zu 2 Felder",
  cardAttackWaechter: "Hieb",
  cardAttackWaechterHint: "Angriff auf angrenzendes Feld",
  cardSpecialWaechter: "Schildwall",
  cardSpecialWaechterHint: "Schild + zwingt Gegner in der Nähe dich anzugreifen",
  cardAttackWildhueter: "Zielschuss",
  cardAttackWildhueterHint: "Fernangriff bis 3 Felder",
  cardSpecialWildhueter: "Fallenpfeil",
  cardSpecialWildhueterHint: "Trifft ein Ziel + angrenzende Gegner",
  cancelTarget: "Abbrechen",
  pickTarget: "Wähle ein Zielfeld",
  win: "Sieg! Das Dorf ist gerettet.",
  lose: "Niederlage – die Helden sind gefallen.",
  playAgain: "Nochmal spielen",
  connecting: "Verbinde…",
  disconnected: "Verbindung verloren – versuche erneut…",
  hpLabel: "LP",
  logLabel: "Verlauf",
};
