export const STR = {
  title: "Tafelrunde",
  waitingHeadline: "Warte auf Mitspieler…",
  waitingHint: "Teile den Einladungslink unten. Sobald ihr bereit seid, tippt der erste Spieler auf „Los geht's“ – ihr könnt auch allein starten.",
  startBtn: "Los geht's",
  inviteLabel: "Einladungslink:",
  spectating: "Du schaust zu",
  yourTurn: "Du bist dran",
  yourTurnStep2: "Du bist dran – 2. Zug der Karte wählen",
  waitingForTurn: (name) => `${name} ist am Zug`,
  enemyPhase: "Die Gegner sind am Zug…",
  roundLabel: (n) => `Runde ${n}`,
  heroNames: { waechter: "Wächter", wildhueter: "Wildhüter" },
  enemyNames: { raider: "Plünderer", archer: "Bogenschütze", captain: "Hauptmann" },

  cards: {
    ansturm: { name: "Ansturm", hint: "1. Vorstoß bis 2 Felder  ·  2. Nahkampf-Angriff (+3)" },
    schildhieb: { name: "Schildhieb", hint: "1. Nahkampf-Angriff (+2)  ·  2. Schild +3" },
    rueckzug: { name: "Rückzug", hint: "1. Nahkampf-Angriff (+2)  ·  2. 1 Feld zurückweichen" },
    sprungschuss: { name: "Sprungschuss", hint: "1. Vorstoß bis 2 Felder  ·  2. Fernangriff bis 2 Felder (+2)" },
    sicherung: { name: "Sicherung", hint: "1. Fernangriff bis 2 Felder (+2)  ·  2. Schild +2" },
    explosivpfeil: { name: "Explosivpfeil", hint: "1. Fernangriff bis 2 Felder (+2)  ·  2. Streuschaden auf Nachbarn (+1)" },
  },
  stepPickMove: "Schritt {n}: Zielfeld zum Ziehen wählen",
  stepPickAttack: "Schritt {n}: Gegner zum Angreifen wählen",

  enemyMoves: {
    vorstoss: "Vorstoß",
    wutschlag: "Wutschlag",
    zielschuss: "Zielschuss",
    rueckzugsschuss: "Rückzugsschuss",
    wuchtschlag: "Wuchtschlag",
    wirbelangriff: "Wirbelangriff",
  },

  cancelTarget: "Abbrechen",
  win: "Sieg! Das Dorf ist gerettet.",
  lose: "Niederlage – die Helden sind gefallen.",
  playAgain: "Nochmal spielen",
  connecting: "Verbinde…",
  disconnected: "Verbindung verloren – versuche erneut…",
  hpLabel: "LP",
  logLabel: "Verlauf",
};
