"""Embed mjolnir/assets/*.webp and sprites.json into index.html.

The game stays a single self-contained file. Run after adding or replacing
images in assets/:  python3 mjolnir/tools/embed_assets.py
Anything without an image keeps its code-drawn fallback.
"""
import base64
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
HTML = ROOT / "index.html"

data = {p.stem: "data:image/webp;base64," + base64.b64encode(p.read_bytes()).decode()
        for p in sorted(ASSETS.glob("*.webp"))}
meta = json.loads((ASSETS / "sprites.json").read_text())
block = ("/* EMBEDDED-ASSETS:BEGIN (generated by tools/embed_assets.py, do not edit by hand) */\n"
         f"const ASSET_DATA = {json.dumps(data)};\n"
         f"const SPRITE_META = {json.dumps(meta)};\n"
         "/* EMBEDDED-ASSETS:END */")
html = HTML.read_text()
html, n = re.subn(r"/\* EMBEDDED-ASSETS:BEGIN.*?EMBEDDED-ASSETS:END \*/", lambda m: block, html, flags=re.S)
assert n == 1, "marker block not found in index.html"
HTML.write_text(html)
print(f"embedded {len(data)} images ({sum(len(v) for v in data.values()) // 1024} KB)")
